name: 'JWT Generator'
description: 'Generate JWT tokens (JSON Web Tokens)'
author: 'Marton Papp <morz@morz.hu>'
inputs:
  secret:
    description: 'The shared secret used to sign the JWTs'
  payload:
    description: 'The payload to encrypt'
outputs:
  jwtToken:
    description: 'Generated JWT Token'
runs:
  using: 'node12'
  main: 'lib/main.js'
