name: 'JWT Generator with options (Node16)'
description: 'Generate JWT tokens (JSON Web Tokens)'
author: 'herculesjr'
inputs:
  secret:
    description: 'The shared secret used to sign the JWTs'
  payload:
    description: 'The payload to encrypt'
  options:
    description: 'The jsonwebtoken options object'
  envVar:
    description: 'Name of the environment variable to output'
# outputs:
#   token:
#     description: 'Generated JWT Token'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'yellow'
